GET https://cuniteu5q0.execute-api.us-east-1.amazonaws.com

###

GET https://cuniteu5q0.execute-api.us-east-1.amazonaws.com/hello

###

POST https://5z499ageih.execute-api.us-east-2.amazonaws.com
Content-Type: application/json

{
"position": "8/5k2/3p4/1p1Pp2p/pP2Pp1P/P4P1K/8/8 b - - 99 50"
}